Tests passes except for last one:
/Users/sas/Projects/CoPilotPlugin/CoPilotPluginTests/DocClientServerTests.swift:120: error: -[CoPilotPluginTests.DocClientServerTests test_sync_back] : failed - expected to eventually equal <bar>, got <foobar>

-> need to re-broadcast all received changes down to the clients