Added `test_handshake_RabbitSocket` which is testing the .Name -> .Doc exchange from client -> server -> client on client connect. This passes reliably while `test_docServerComms` which is the same with DocServer on one end fails.
Test log:
Test Suite 'All tests' started at 2015-11-15 17:56:42.414
Test Suite 'CoPilotTests.xctest' started at 2015-11-15 17:56:42.415
Test Suite 'BonjourTests' started at 2015-11-15 17:56:42.416
Test Case '-[CoPilotTests.BonjourTests test_Browser_add_remove]' started.
Test Case '-[CoPilotTests.BonjourTests test_Browser_add_remove]' passed (3.951 seconds).
Test Case '-[CoPilotTests.BonjourTests test_publish]' started.
Test Case '-[CoPilotTests.BonjourTests test_publish]' passed (0.002 seconds).
Test Case '-[CoPilotTests.BonjourTests test_resolve]' started.
Test Case '-[CoPilotTests.BonjourTests test_resolve]' passed (0.037 seconds).
Test Suite 'BonjourTests' passed at 2015-11-15 17:56:46.407.
	 Executed 3 tests, with 0 failures (0 unexpected) in 3.989 (3.991) seconds
Test Suite 'CommandTests' started at 2015-11-15 17:56:46.408
Test Case '-[CoPilotTests.CommandTests test_serialize_Cursor]' started.
Test Case '-[CoPilotTests.CommandTests test_serialize_Cursor]' passed (0.001 seconds).
Test Case '-[CoPilotTests.CommandTests test_serialize_Doc]' started.
Test Case '-[CoPilotTests.CommandTests test_serialize_Doc]' passed (0.001 seconds).
Test Case '-[CoPilotTests.CommandTests test_serialize_GetDocument]' started.
Test Case '-[CoPilotTests.CommandTests test_serialize_GetDocument]' passed (0.001 seconds).
Test Case '-[CoPilotTests.CommandTests test_serialize_GetVersion]' started.
Test Case '-[CoPilotTests.CommandTests test_serialize_GetVersion]' passed (0.001 seconds).
Test Case '-[CoPilotTests.CommandTests test_serialize_Name]' started.
Test Case '-[CoPilotTests.CommandTests test_serialize_Name]' passed (0.001 seconds).
Test Case '-[CoPilotTests.CommandTests test_serialize_Undefined]' started.
Test Case '-[CoPilotTests.CommandTests test_serialize_Undefined]' passed (0.001 seconds).
Test Case '-[CoPilotTests.CommandTests test_serialize_Update]' started.
Test Case '-[CoPilotTests.CommandTests test_serialize_Update]' passed (0.003 seconds).
Test Case '-[CoPilotTests.CommandTests test_serialize_Version]' started.
Test Case '-[CoPilotTests.CommandTests test_serialize_Version]' passed (0.001 seconds).
Test Suite 'CommandTests' passed at 2015-11-15 17:56:46.440.
	 Executed 8 tests, with 0 failures (0 unexpected) in 0.008 (0.032) seconds
Test Suite 'ConnectionManagerTests' started at 2015-11-15 17:56:46.440
Test Case '-[CoPilotTests.ConnectionManagerTests test_connected_published_subscribed]' started.
2015-11-15 17:56:46.504 xctest[47676:1986741] Trying to save a document without any appropriate writable type defined.
Test Case '-[CoPilotTests.ConnectionManagerTests test_connected_published_subscribed]' passed (0.069 seconds).
Test Case '-[CoPilotTests.ConnectionManagerTests test_filters]' started.
2015-11-15 17:56:46.520 xctest[47676:1986741] Trying to save a document without any appropriate writable type defined.
Test Case '-[CoPilotTests.ConnectionManagerTests test_filters]' passed (0.012 seconds).
Test Case '-[CoPilotTests.ConnectionManagerTests test_subscribe_url]' started.
Test Case '-[CoPilotTests.ConnectionManagerTests test_subscribe_url]' passed (0.058 seconds).
Test Suite 'ConnectionManagerTests' passed at 2015-11-15 17:56:46.582.
	 Executed 3 tests, with 0 failures (0 unexpected) in 0.139 (0.141) seconds
Test Suite 'DiffTests' started at 2015-11-15 17:56:46.583
Test Case '-[CoPilotTests.DiffTests test_adjustPos]' started.
Test Case '-[CoPilotTests.DiffTests test_adjustPos]' passed (0.013 seconds).
Test Case '-[CoPilotTests.DiffTests test_apply_Document]' started.
Test Case '-[CoPilotTests.DiffTests test_apply_Document]' passed (0.002 seconds).
Test Case '-[CoPilotTests.DiffTests test_apply_Document_conflict]' started.
Test Case '-[CoPilotTests.DiffTests test_apply_Document_conflict]' passed (0.002 seconds).
Test Case '-[CoPilotTests.DiffTests test_apply_Document_diverged]' started.
Test Case '-[CoPilotTests.DiffTests test_apply_Document_diverged]' passed (0.001 seconds).
Test Case '-[CoPilotTests.DiffTests test_apply_Document_diverged2]' started.
Test Case '-[CoPilotTests.DiffTests test_apply_Document_diverged2]' passed (0.002 seconds).
Test Case '-[CoPilotTests.DiffTests test_apply_Document_diverged3]' started.
Test Case '-[CoPilotTests.DiffTests test_apply_Document_diverged3]' passed (0.001 seconds).
Test Case '-[CoPilotTests.DiffTests test_apply_error]' started.
Test Case '-[CoPilotTests.DiffTests test_apply_error]' passed (0.003 seconds).
Test Case '-[CoPilotTests.DiffTests test_apply_String]' started.
Test Case '-[CoPilotTests.DiffTests test_apply_String]' passed (0.001 seconds).
Test Case '-[CoPilotTests.DiffTests test_computeDiff]' started.
Test Case '-[CoPilotTests.DiffTests test_computeDiff]' passed (0.001 seconds).
Test Case '-[CoPilotTests.DiffTests test_hash]' started.
Test Case '-[CoPilotTests.DiffTests test_hash]' passed (0.001 seconds).
Test Case '-[CoPilotTests.DiffTests test_merge]' started.
Test Case '-[CoPilotTests.DiffTests test_merge]' passed (0.011 seconds).
Test Case '-[CoPilotTests.DiffTests test_merge_failure]' started.
Test Case '-[CoPilotTests.DiffTests test_merge_failure]' passed (0.009 seconds).
Test Case '-[CoPilotTests.DiffTests test_patches]' started.
Test Case '-[CoPilotTests.DiffTests test_patches]' passed (0.001 seconds).
Test Case '-[CoPilotTests.DiffTests test_patches_long]' started.
Test Case '-[CoPilotTests.DiffTests test_patches_long]' passed (0.003 seconds).
Test Case '-[CoPilotTests.DiffTests test_preserve_position]' started.
Test Case '-[CoPilotTests.DiffTests test_preserve_position]' passed (0.049 seconds).
Test Suite 'DiffTests' passed at 2015-11-15 17:56:46.719.
	 Executed 15 tests, with 0 failures (0 unexpected) in 0.098 (0.137) seconds
Test Suite 'DocClientServerTests' started at 2015-11-15 17:56:46.720
Test Case '-[CoPilotTests.DocClientServerTests test_conflict_client_update]' started.
#### server cmd: .Name DocClient
#### DocClient cmd: .Doc
#### server cmd: .Update Changeset (cc51b81974287ab79cef9e94fe778cc9 [@@ -1,7 +1,6 @@
-initial
+client
])
#### DocClient cmd: .Doc
Test Case '-[CoPilotTests.DocClientServerTests test_conflict_client_update]' passed (1.378 seconds).
Test Case '-[CoPilotTests.DocClientServerTests test_conflict_server_update]' started.
#### server cmd: .Name DocClient
#### DocClient cmd: .Doc
#### DocClient cmd: .Update Changeset (cc51b81974287ab79cef9e94fe778cc9 [@@ -1,7 +1,6 @@
-initial
+server
])
#### server cmd: .GetDoc
#### DocClient cmd: .Doc
Test Case '-[CoPilotTests.DocClientServerTests test_conflict_server_update]' passed (0.568 seconds).
Test Case '-[CoPilotTests.DocClientServerTests test_connect_url]' started.
#### server cmd: .Name DocClient
#### DocClient cmd: .Doc
Test Case '-[CoPilotTests.DocClientServerTests test_connect_url]' passed (0.012 seconds).
Test Case '-[CoPilotTests.DocClientServerTests test_nsNetService]' started.
#### server cmd: .Name DocClient
#### DocClient cmd: .Doc
Test Case '-[CoPilotTests.DocClientServerTests test_nsNetService]' passed (0.033 seconds).
Test Case '-[CoPilotTests.DocClientServerTests test_sendChanges]' started.
#### server cmd: .Name DocClient
#### DocClient cmd: .Doc
#### server cmd: .Name DocClient
#### DocClient cmd: .Doc
#### DocClient cmd: .Update Changeset (acbd18db4cc2f85cedef654fccc4a4d8 [@@ -1,3 +1,6 @@
 foo
+bar
])
#### DocClient cmd: .Update Changeset (acbd18db4cc2f85cedef654fccc4a4d8 [@@ -1,3 +1,6 @@
 foo
+bar
])
Test Case '-[CoPilotTests.DocClientServerTests test_sendChanges]' passed (0.542 seconds).
Test Case '-[CoPilotTests.DocClientServerTests test_server]' started.
Test Case '-[CoPilotTests.DocClientServerTests test_server]' passed (0.209 seconds).
Test Case '-[CoPilotTests.DocClientServerTests test_sync_back]' started.
#### server cmd: .Name DocClient
#### DocClient cmd: .Doc
#### server cmd: .Name DocClient
#### DocClient cmd: .Doc
#### DocClient cmd: .Update Changeset (acbd18db4cc2f85cedef654fccc4a4d8 [@@ -1,3 +1,6 @@
 foo
+bar
])
#### DocClient cmd: .Update Changeset (acbd18db4cc2f85cedef654fccc4a4d8 [@@ -1,3 +1,6 @@
 foo
+bar
])
#### server cmd: .Update Changeset (3858f62230ac3c915f300c664312c63f [@@ -1,6 +1,3 @@
-foo
 bar
])
#### DocClient cmd: .Update Changeset (3858f62230ac3c915f300c664312c63f [@@ -1,6 +1,3 @@
-foo
 bar
])
Test Case '-[CoPilotTests.DocClientServerTests test_sync_back]' passed (1.102 seconds).
Test Suite 'DocClientServerTests' passed at 2015-11-15 17:56:50.570.
	 Executed 7 tests, with 0 failures (0 unexpected) in 3.843 (3.850) seconds
Test Suite 'IssueTests' started at 2015-11-15 17:56:50.571
Test Case '-[CoPilotTests.IssueTests test_issue_14]' started.
#### server cmd: .Name DocClient
#### DocClient cmd: .Doc
#### server cmd: .Name DocClient
#### DocClient cmd: .Doc
#### server cmd: .Update Changeset (acbd18db4cc2f85cedef654fccc4a4d8 [@@ -1,3 +1,3 @@
-foo
+bar
])
#### DocClient cmd: .Update Changeset (acbd18db4cc2f85cedef654fccc4a4d8 [@@ -1,3 +1,3 @@
-foo
+bar
])
#### DocClient cmd: .Update Changeset (37b51d194a7513e45b56f6524f2d51f2 [@@ -1,3 +1,3 @@
-bar
+foo
])
#### DocClient cmd: .Update Changeset (37b51d194a7513e45b56f6524f2d51f2 [@@ -1,3 +1,3 @@
-bar
+foo
])
Test Case '-[CoPilotTests.IssueTests test_issue_14]' passed (1.103 seconds).
Test Case '-[CoPilotTests.IssueTests test_issue_36]' started.
Test Case '-[CoPilotTests.IssueTests test_issue_36]' passed (0.007 seconds).
Test Case '-[CoPilotTests.IssueTests test_issue_7]' started.
Test Case '-[CoPilotTests.IssueTests test_issue_7]' passed (0.002 seconds).
Test Case '-[CoPilotTests.IssueTests test_issue_8]' started.
Test Case '-[CoPilotTests.IssueTests test_issue_8]' passed (0.001 seconds).
Test Suite 'IssueTests' passed at 2015-11-15 17:56:51.685.
	 Executed 4 tests, with 0 failures (0 unexpected) in 1.112 (1.115) seconds
Test Suite 'RabbitServerTests' started at 2015-11-15 17:56:51.686
Test Case '-[CoPilotTests.RabbitServerTests test_docServerComms]' started.
starting RabbitServer
starting RabbitServer
sending client name
client received: .Name client
stopping RabbitServer
/Users/sas/Projects/CoPilot/CoPilotTests/RabbitServerTests.swift:178: error: -[CoPilotTests.RabbitServerTests test_docServerComms] : failed - expected to eventually be true, got <false>

Test Case '-[CoPilotTests.RabbitServerTests test_docServerComms]' failed (5.027 seconds).
Test Case '-[CoPilotTests.RabbitServerTests test_handshake_RabbitSocket]' started.
Test Case '-[CoPilotTests.RabbitServerTests test_handshake_RabbitSocket]' passed (0.016 seconds).
Test Case '-[CoPilotTests.RabbitServerTests test_socket]' started.
Test Case '-[CoPilotTests.RabbitServerTests test_socket]' passed (0.015 seconds).
Test Case '-[CoPilotTests.RabbitServerTests test_socket_3way]' started.
Test Case '-[CoPilotTests.RabbitServerTests test_socket_3way]' passed (0.021 seconds).
Test Suite 'RabbitServerTests' failed at 2015-11-15 17:56:56.767.
	 Executed 4 tests, with 1 failure (0 unexpected) in 5.079 (5.081) seconds
Test Suite 'ServerTests' started at 2015-11-15 17:56:56.768
Test Case '-[CoPilotTests.ServerTests test_broadcast]' started.
Test Case '-[CoPilotTests.ServerTests test_broadcast]' passed (0.034 seconds).
Test Case '-[CoPilotTests.ServerTests test_send]' started.
Test Case '-[CoPilotTests.ServerTests test_send]' passed (0.024 seconds).
Test Case '-[CoPilotTests.ServerTests test_sendChanges]' started.
Test Case '-[CoPilotTests.ServerTests test_sendChanges]' passed (0.025 seconds).
Test Case '-[CoPilotTests.ServerTests test_server]' started.
Test Case '-[CoPilotTests.ServerTests test_server]' passed (0.012 seconds).
Test Suite 'ServerTests' passed at 2015-11-15 17:56:56.865.
	 Executed 4 tests, with 0 failures (0 unexpected) in 0.094 (0.097) seconds
Test Suite 'CoPilotTests.xctest' failed at 2015-11-15 17:56:56.865.
	 Executed 48 tests, with 1 failure (0 unexpected) in 14.362 (14.450) seconds
Test Suite 'All tests' failed at 2015-11-15 17:56:56.866.
	 Executed 48 tests, with 1 failure (0 unexpected) in 14.362 (14.451) seconds

Test session log:
	/var/folders/by/sp45g7x53_3bxhb1ny0v6_n40000gn/T/com.apple.dt.XCTest-status/Session-2015-11-15_17:56:39-QEelmy.log

Program ended with exit code: 1